java geraTeste config0.txt
java geraTeste config1.txt
java geraTeste config2.txt
java geraTeste config3.txt
java geraTeste config4.txt
java geraTeste config5.txt
java geraTeste config6.txt
java geraTeste config7.txt
java geraTeste config8.txt
java geraTeste config9.txt